# Generated by Django 4.2.3 on 2025-07-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='fecha',
            new_name='fecha_publicacion',
        ),
    ]
